# Global settings applied to the whole site.
[build]
  base    = ""
  publish = "public"
  command = "yarn build"

# Production context: All deploys to the main
# repository branch will inherit these settings.
[context.production.environment]
  NODE_VERSION = "12.13.1"
  NODE_ENV = "production"
  YARN_VERSION = "1.22.4"

# Deploy Preview context: All Deploy Previews
# will inherit these settings.
[context.deploy-preview.environment]
  NODE_VERSION = "12.13.1"
  NODE_ENV = "production"
  YARN_VERSION = "1.22.4"

# Branch Deploy context: All Branch Deploys
# will inherit these settings.
[context.branch-deploy.environment]
  NODE_VERSION = "12.13.1"
  NODE_ENV = "production"
  YARN_VERSION = "1.22.4"
