name: Trigger Netlify Build
on:
  schedule:
    # Runs every hour
    - cron: '* * * * *'
jobs:
  build:
    name: Request Netlify Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Curl request
        run: curl -X POST -d {} https://api.netlify.com/build_hooks/5e7ef92cd2979df57c272aaf